# Generated by Django 3.0.2 on 2020-02-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uerPassword',
            new_name='userPassword',
        ),
    ]
