# Generated by Django 3.0.2 on 2020-03-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200219_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
