# Generated by Django 3.0.2 on 2020-03-07 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='testNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_id', models.IntegerField()),
                ('num_id2', models.IntegerField()),
                ('num_type', models.CharField(default='Y', max_length=2)),
                ('num_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 7, 17, 19, 37, 59574))),
            ],
        ),
    ]
