# Generated by Django 3.0.2 on 2020-03-10 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_testnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnum',
            name='num_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 10, 22, 1, 37, 452153)),
        ),
    ]
