# Generated by Django 3.0.2 on 2020-03-15 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200315_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnum',
            name='num_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 15, 21, 18, 8, 863147)),
        ),
    ]
